weights: yolov5s.pt
cfg: "D:\\\u5927\u5B66\\\u5927\u4E09\\\u5B66\u4E60\\\u8BA1\u7B97\u673A\u89C6\u89C9\
  \\HW1\\yolov5-6.0\\yolov5-6.0\\models\\yolov5s_my.yaml"
data: my.yaml
hyp: data\hyps\hyp.scratch.yaml
epochs: 200
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\exp7
